name: Tag Push

on:
  push:
    tags:
      - v*
  workflow_dispatch: {}

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Run on github.ref == ${{ github.ref }}
        run: pwd; find
